### ISSUE TITLE
crash on throwing empty toke in to cauldron [1.16.1]

### ISSUE THREAD

**Issue by SDUBZ** [2xsaiko/lacrimis#2]
Patchouli_release-1.16-37-fabric-1.16-37.1-FABRIC

lacrimis-1.1.0
logs:
[crash-2020-07-03_22.33.42-client.txt](https://github.com/2xsaiko/lacrimis/files/4869847/crash-2020-07-03_22.33.42-client.txt)
[latest.log](https://github.com/2xsaiko/lacrimis/files/4869850/latest.log)

**Comment by dblsaiko** [comment]
Hopefully fixed in 88e9855. Can't build it yet though because jitpack is down.
