### ISSUE TITLE
Mod crashes attempting to access clientside code on serverside.

### ISSUE THREAD

**Issue by queenofthebees** [2xsaiko/lacrimis#3]
Importing/referencing clientside-only classes in common classes causes crashes on dedicated servers. This is most notably apparent in a ClassNotFoundException at server boot due to not finding these classes. I tested a quick-fix involving just removing all clientside code from the server's source, which fixed it.

As far as I can tell, the most effective fix would be to separate the server/common and client versions of the ModEntityTypes, ModCrafting, ModNetworking, and ModParticles classes.

**Comment by stuin** [comment]
Yeah, that seems about right. I did not remember to test server side stuff at all. Give me a bit.
