### ISSUE TITLE
[1.17] Random crash while waiting for tears to fill a crucible

### ISSUE THREAD

**Issue by Desempregago** [2xsaiko/lacrimis#4]
I can't find the exact source of the problem, but the log mentions `tickgoals` and `fillPatchouliContext`, and I have 2 mods that relies on Patchouli, but I'm only using Lacrimis at the moment.

[Crash Report](https://pastebin.com/ceHtUZak)

**Comment by Desempregago** [comment]
PS: I don't know if it IS REALLY Lacrimis that is causing it, but it's the mod that I'm most deep into.

**Comment by stuin** [comment]
I will look into it, but I am not sure myself looking at the log. It mentions a pillager and Lacrimis should not be doing anything with them, but I can't say for certain it is not Lacrimis. If you think of or notice any other details about the situation the crash happened in let me know.

**Comment by Desempregago** [comment]
Found the culprit, it was Nyv's Quivers.

I have a slight issue with Lacrimis. Why are the blocks VERY HARD to break + not dropping themselves on break?

**Comment by Desempregago** [comment]
blocks from lacrimis take too long to break and they simply disappear after breaking (no drops)

**Comment by stuin** [comment]
Most of them should work with a plain pickaxe, but the interactive blocks are enchanting table hardness at the moment. I admit that might be a bit much.

**Comment by Desempregago** [comment]
but the problem revolves around the blocks NOT dropping when breaking
I had to make two sets of tier 1 runestones because I broke one tier 1 runestone to make a duct connector and it didn't drop as an item

**Comment by stuin** [comment]
So issue has been found and fixed, but you probably will have to wait another day for the download, as there are a few other errors I am trying to fix.

**Comment by Desempregago** [comment]
No problem, take your time. I'm having quite a bit of fun with Lacrimis so far..

on a side note, is there any way to get crying obsidian rather than piglin bartering or finding ruined portals?

**Comment by stuin** [comment]
I should probably make it more clear that I added crying obsidian into the end pillars.
