### ISSUE TITLE
[1.16.5] Warding Rune does not create Warded Rune blocks

### ISSUE THREAD

**Issue by Infinidoge** [2xsaiko/lacrimis#5]
I'm trying to create Warded Runes, using a properly build tier 3 soul cage and the Warding Rune, however, all methods I've tried of creating the warded runes have failed:
- Placing around the soul cage
- Dropping on the soul cage
- Holding while on the soul cage
- Etc.

Using the warding rune to enchant the tear-soaked armor worked successfully, though.

This was reproduced on 1.16.5 with Lacrimis 2.0.2

**Comment by stuin** [comment]
Place a rune block directly on top of the warding rune and activate it. Keep in mind that the only way to move the block afterwards is to use the rune again.

**Comment by Infinidoge** [comment]
That doesn't seem to work either. 
![2021-07-02_22 42 51](https://user-images.githubusercontent.com/22727114/124340941-eb04e800-db86-11eb-9283-f6dde61aa2d6.png)

(Then right clicked on the rest of the soul cage, and also went under and right clicked the middle, to check.)

**Comment by stuin** [comment]
Make sure you are supplying enough tears, but I will look into it

**Comment by Infinidoge** [comment]
I have it connected to both a full crucible and the Block of Eternal Sadness, so I don't think that is the issue.

Though, what might be the issue are these lines [here](https://github.com/2xsaiko/lacrimis/blob/0bd27bd37912b008ec4889d16eaea2edf9a98d5d/src/main/java/modfest/lacrimis/block/rune/WardingBlock.java#L20-L27)

They appear to reference the blocks position, which I would presume to be referring to the Warding Rune itself, therefore not checking the state of the block above.

**Comment by stuin** [comment]
Welp I fixed the issue in 1.17 but I forgot to do the same in 1.16. Give me a few minutes

**Comment by stuin** [comment]
New version is up on curseforge, sorry about that

**Comment by Infinidoge** [comment]
It's no problem, thanks!
